-- Extra FeeType values: DONATE / TIP_UNWALLETED / BOOST fund the rewards pool at 100%.
ALTER TYPE "FeeType" ADD VALUE IF NOT EXISTS 'DONATE';
ALTER TYPE "FeeType" ADD VALUE IF NOT EXISTS 'TIP_UNWALLETED';
ALTER TYPE "FeeType" ADD VALUE IF NOT EXISTS 'BOOST';
